### ISSUE TITLE
Comment for the explanation doesn't always work correctly

### ISSUE THREAD

**Issue by Stoffberg** [VaibhavAcharya/code-gpt#2]
![image](https://user-images.githubusercontent.com/48858949/218042122-fbe4b4aa-a911-496b-a9bf-c1b627262d1b.png)
I might be able to help with this, how are you currently determining the type of comment?

**Comment by crevulus** [comment]
For me the commenting worked at the top level, but once I was highlighting a function inside another function I got the same issue

<img width="1236" alt="Screenshot 2023-02-10 at 09 58 48" src="https://user-images.githubusercontent.com/50107046/218062133-b88062a7-8fe2-49c2-8eea-9a71075caa00.png">

**Comment by VaibhavAcharya** [comment]
currently sending the `languageID` along with the input and giving it to the prompt to generate the comment.
but it is not really good at it. 😅

**Comment by Stoffberg** [comment]
What are you using on the backend to generate the prompt, because it might be worthwhile to just manually detect which language they are using in vscode and the lookup the commenting strategy in a predefined hashmap instead of letting the backend generate it?

**Comment by VaibhavAcharya** [comment]
Server is on remix.run which then calls OpenAI's `text-davinci-003` model.

**Comment by Stoffberg** [comment]
@VaibhavAcharya A fix have been implemented in #3, just look at the breaking changes to the backend.
